### ISSUE TITLE
[Bug]: Beta and Release ArcAPI's seem to be synchronized somehow?

### ISSUE THREAD

**Issue by NikNikovsky** [IzK-ArcOS/ArcOS-Frontend#100]
### What happened?

So, I made an account on the beta ArcAPI, applied everything, etc.
But when I came to the normal ArcAPI, everything was synced.
I think that is because you are using the same API (community.arcapi.nl) for both versions.
Do feel free to correct me though.

### Edition

Website

### If you are using a browser, which browsers are you seeing the problem on?

Chrome

### Contact Detail(s)

@NikNikovsky

**Comment by ghost** [comment]
beta and web use the same arcapi

**Comment by NikNikovsky** [comment]
...but they shouldn't be synchronized?

**Comment by IzKuipers** [comment]
the frontend is the only difference, what API it uses is completely up to the user. Closing.

**Comment by NikNikovsky** [comment]
(why does my browser say "1 hour ago" on all these?)

**Comment by ghost** [comment]
> @NikNikovsky: (why does my browser say "1 hour ago" on all these?)

I don't know.
