### ISSUE TITLE
Cannot pick a profile picture via Settings flow

### ISSUE THREAD

**Issue by eversiege** [IzK-ArcOS/ArcOS-Frontend#101]
### What happened?

@Blockyheadman reported that the window to choose a new profile picture does not appear under standard settings flow. Yet to replicate. 

### Edition

Website

### ArcOS Version

web.izk-ArcOS.nl

### If you are using a browser, which browsers are you seeing the problem on?

Chrome

### Other Browser(s)

Chromium engine

### Contact Detail(s)

Blocky, Eversiege

**Comment by IzKuipers** [comment]
please check the bottom of the release notes of 5.0.11.

**Comment by nulqwy** [comment]
> please check the bottom of the release notes of 5.0.11.

regression? :pensive:

**Comment by IzKuipers** [comment]
what?

**Comment by nulqwy** [comment]
> A software regression is a type of software bug where a feature that has worked before stops working. This may happen after changes are applied to the software's source code, including the addition of new features and bug fixes.

source: [wikipedia](https://en.wikipedia.org/wiki/Software_regression)

**Comment by logangamesdaily** [comment]
Can confirm, happens to me.

**Comment by NikNikovsky** [comment]
Can confirm on Firefox and duckduckgo

**Comment by nulqwy** [comment]
guys, its a known issue (a regression)

**Comment by IzKuipers** [comment]
1) not providing support for firefox
2) known issue, already solved ages ago, closing

**Comment by NikNikovsky** [comment]
Still broken on Opera.
Refreshed the page and cleaned the cookies.![Screenshot_2023-11-07-22-43-42-376_com.opera.browser.jpg](https://github.com/IzK-ArcOS/ArcOS-Frontend/assets/75254052/bf78ceb3-9f4a-4734-b6be-e9f419086f5b)

**Comment by IzKuipers** [comment]
web.izk-arcos.nl won't be updated until the release of 5.0.12. This is NOT a bug.

**Comment by NikNikovsky** [comment]
My bad

**Comment by IzKuipers** [comment]
https://github.com/IzK-ArcOS/ArcOS-Frontend/commit/c743f8f6e8416b9871a15a9d35c9034759e261f1
