### ISSUE TITLE
[Bug]: File Manager sending unnecesarilly many requests to the backend upon folder refresh

### ISSUE THREAD

**Issue by nulqwy** [IzK-ArcOS/ArcOS-Frontend#102]
### What happened?

When refreshing folder, ~~backend~~ frontend will make, in total:
- 3 requests to `/fs/quota`
- 6 requests to `/fs/dir/get` (requesting `./` ie home directory)
- 1 requst to `/fs/dir/get` (requesting the folder being refreshed)

ie it makes 5 unnecesary requests to `/fs/dir/get` as well as 2 more to `/fs/quota`

### Edition

Website

### ArcOS Version

v5.0.11-development (cf0a158)

### If you are using a browser, which browsers are you seeing the problem on?

Chrome

### Contact Detail(s)

@spaceginner (discord), ivan.demian2009@gmail.com

**Comment by nulqwy** [comment]
Devtool screenshot in networking tab:
![image](https://github.com/IzK-ArcOS/ArcOS-Frontend/assets/97038786/9afc6787-7d1c-4a2b-af2e-f90351952e36)

**Comment by ghost** [comment]
I believe this is a serious issue.

**Comment by nulqwy** [comment]
it doesnt send like 100 requests, and refreshing is not done particularly often either, so it is just something that shouldnt be ignored but neither important

**Comment by IzKuipers** [comment]
Closing this as ArcOS v5 production is stopping as of February 20th 2024.
