### ISSUE TITLE
Better handle failed sideloading

### ISSUE THREAD

**Issue by ArcBugRep** [IzK-ArcOS/ArcOS-Frontend#103]
File: TypeError 

Failed to fetch dynamically imported module: http://[ip]/ArcStore/install.js

TypeError: Failed to fetch dynamically imported module: http://[ip]/ArcStore/install.js

> References br$784478-810985-217364-186446

**Comment by logangamesdaily** [comment]
haha this was me, multiple times

**Comment by logangamesdaily** [comment]
it was because of http/https mismatch
