### ISSUE TITLE
A few features that would be useful

### ISSUE THREAD

**Issue by logangamesdaily** [IzK-ArcOS/ArcOS-Frontend#104]
### Describe the new feature

1. Right click context menu for a file should have `Open With`
2. Markdown Viewer and Media Player should be able to be opened from the desktop and, like Text Editor, load files through a button.

### Describe why the feature is useful

1. Useful to open certain files with other apps.
2. Just a simple QoL fix that should’ve been there already.

**Comment by ghost** [comment]
I agree with this
