### ISSUE TITLE
[Feature]: Add music and/or images to a user's folder by default

### ISSUE THREAD

**Issue by NikNikovsky** [IzK-ArcOS/ArcOS-Frontend#105]
### Describe the new feature

You could use stock music, stock images. etc.
(or not, I got suggestions on what you could use)

### Describe why the feature is useful

It would be useful for people who just want to quickly test out the system and its capabilities.
(obviously, the preloaded stuff is undownloadable)

**Comment by ghost** [comment]
Maybe like a `stock` folder with random stock images and stuff from the internet, which you can then copy onto arcfs

**Comment by NikNikovsky** [comment]
But like, Wii still have 2 things left to discuss:
- How do Wii protect the files from being downloaded
- What do Wii throw in there?

**Comment by NikNikovsky** [comment]
Let's insert Scarlet Fire because yes.

**Comment by IzKuipers** [comment]
This is done using filesystem templates in the backend, it's up to the server admin to include preloaded documents and such

**Comment by ghost** [comment]
> This is done using filesystem templates in the backend, it's up to the server admin to include preloaded documents and such

alright

**Comment by NikNikovsky** [comment]
> This is done using filesystem templates in the backend, it's up to the server admin to include preloaded documents and such 

I forgot to mention that I wanted it on the community API

**Comment by ghost** [comment]
> > This is done using filesystem templates in the backend, it's up to the server admin to include preloaded documents and such
> 
> I forgot to mention that I wanted it on the community API

then I got no idea
