### ISSUE TITLE
OA kills the taskbar

### ISSUE THREAD

**Issue by ArcBugRep** [IzK-ArcOS/ArcOS-Frontend#106]
this is really just confirmation that report fo4b0ww47jlzull is correct.

> References br$376205-539765-377313-340532

**Comment by IzKuipers** [comment]
I put this here to definitively say that the `oa` command will be removed from ArcTerm starting in 5.0.12. Any future reports of this command will be removed.

**Comment by ghost** [comment]
> @IzKuipers: I put this here to definitively say that the `oa` command will be removed from ArcTerm starting in 5.0.12. Any future reports of this command will be removed.

Not sure why `oa` even was a command in the first place.

**Comment by IzKuipers** [comment]
It was intended as a test command back in the earliest of early days of ArcOS v5, I just never removed it

**Comment by ghost** [comment]
> @IzKuipers: It was intended as a test command back in the earliest of early days of ArcOS v5, I just never removed it

Oh, I see.
