### ISSUE TITLE
[Bug]: System Crashed at Login Screen

### ISSUE THREAD

**Issue by takuruk1** [IzK-ArcOS/ArcOS-Frontend#107]
### What happened?

I was trying to make an account when suddenly it jus crashed on me, I have attatched the full debug log. From what I can tell, the server returned a code 500 so it might've been just my router acting up on the traffic but just to be sure here I am reporting it.
[errrmmm what.txt](https://github.com/IzK-ArcOS/ArcOS-Frontend/files/13757031/errrmmm.what.txt)

### Edition

Desktop (Specfiy version below)

### ArcOS Version

5.0.11

### Contact Detail(s)

s.takuq on Discord

**Comment by IzKuipers** [comment]
what username did you enter? The servers currently return 500 when there's a username conflict because of a mistake from our BDT.

I think the username may have already existed, please try another username and report back.

**Comment by logangamesdaily** [comment]
I'm pretty sure this was fixed **long** ago.
