### ISSUE TITLE
FileLoaders.editFile is undefined

### ISSUE THREAD

**Issue by ArcBugRep** [IzK-ArcOS/ArcOS-Frontend#108]
File: TypeError 

FileLoaders.editFile is undefined

exec@https://web.izk-arcos.nl/assets/index-6b73fc9a.js:11408:5

> References br$873699-962772-198263-306925

**Comment by andriemc** [comment]
Full crash report (for team members): [`gna91jug88p1d1p`](https://bugrep.arcapi.nl/?rid=gna91jug88p1d1p)

**Comment by andriemc** [comment]
> @andriemc: Full crash report (for team members): [`gna91jug88p1d1p`](https://bugrep.arcapi.nl/?rid=gna91jug88p1d1p)

Also, the user agent is spoofed, since I use Librewolf (Firefox fork, default user agent is a Firefox one). ArcOS shows a black screen when using Firefox.

**Comment by IzKuipers** [comment]
> Full crash report (for team members): [`gna91jug88p1d1p`](https://bugrep.arcapi.nl/?rid=gna91jug88p1d1p)

andrew, why does the `issueId` exist? maybe because you're not supposed to make report IDs publicly available?

**Comment by ghost** [comment]
> andrew, why does the `issueId` exist? maybe because you're not supposed to make report IDs publicly available?

You really are saying that as If someone told me that I shouldn't, which no one did.

**Comment by IzKuipers** [comment]
I thought the `br$<issue-id>` at the bottom of every bugrep issue was a signal

**Comment by ghost** [comment]
> I thought the `br$<issue-id>` at the bottom of every bugrep issue was a signal
> 

It couldve been any id
