### ISSUE TITLE
[Bug]: Accented start button does not work when dock is on side

### ISSUE THREAD

**Issue by 9021007** [IzK-ArcOS/ArcOS-Frontend#111]
### What happened?

I put the dock on the side of the screen and the accented start button disappears. it reappears if i disable accented start button.

![image](https://github.com/IzK-ArcOS/ArcOS-Frontend/assets/24487638/7b0dac8d-2875-4e8a-9953-2e3b9483724a)
![image](https://github.com/IzK-ArcOS/ArcOS-Frontend/assets/24487638/6cfdcf31-b683-4c87-b0f1-6b29102c6bf2)

### Edition

Website

### If you are using a browser, which browsers are you seeing the problem on?

Firefox

### Contact Detail(s)

arcos@9021007.xyz

**Comment by IzKuipers** [comment]
"website" is one thing, what version is another

what frontend is this?

**Comment by ghost** [comment]
> "website" is one thing, what version is another
> 
> what frontend is this?

Actually, this is on Firefox I just realized

**Comment by 9021007** [comment]
![image](https://github.com/IzK-ArcOS/ArcOS-Frontend/assets/24487638/51b974ed-c3e0-4778-8395-81f34b110457)
me when i follow the directions given to me

5.0.12

**Comment by ghost** [comment]
imma try to see if it works on brave (chromium)

**Comment by ghost** [comment]
imma try to see if it works on brave (chromium)

**Comment by IzKuipers** [comment]
> ![image](https://private-user-images.githubusercontent.com/24487638/294107545-51b974ed-c3e0-4778-8395-81f34b110457.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzNTE5MTIsIm5iZiI6MTcwNDM1MTYxMiwicGF0aCI6Ii8yNDQ4NzYzOC8yOTQxMDc1NDUtNTFiOTc0ZWQtYzNlMC00Nzc4LTgzOTUtODFmMzRiMTEwNDU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA0VDA3MDAxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiYTA5ZDY1YWFhNmNjNjQ5ZTA3NGI5MjEyMzQ2MmJhYTIyMTM4MjQzNzM3ZWM3ZmJlNzE1ODM2NTEzNjBhMGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NiFVuwhl2VtIn6ZYzLlt_RelHKOP34CT5sktTsH4eZU) me when i follow the directions given to me
> 
> 5.0.12

web.izk-arcos.nl?

**Comment by 9021007** [comment]
yes

**Comment by 9021007** [comment]
![image](https://github.com/IzK-ArcOS/ArcOS-Frontend/assets/24487638/babd47b3-91fa-4575-ad77-d8f4720a88e1)
reproduced in safari

**Comment by ghost** [comment]
Il try on a chromium browser and see if it happens

**Comment by IzKuipers** [comment]
> Il try on a chromium browser and see if it happens

it does happen

**Comment by IzKuipers** [comment]
in fact, it's there one second, and disappears the next

**Comment by ghost** [comment]
> > Il try on a chromium browser and see if it happens
> 
> it does happen

alright, then this isnt a firefox/safari issue

**Comment by 9021007** [comment]
![image](https://github.com/IzK-ArcOS/ArcOS-Frontend/assets/24487638/e15656f5-7dc1-41bc-8ee1-d986c06b9c67)

**Comment by IzKuipers** [comment]
this is the weirdest thing

**Comment by IzKuipers** [comment]
there's nothing in the codebase that can cause this

this must be an SVG glitch or something

**Comment by IzKuipers** [comment]
![image](https://github.com/IzK-ArcOS/ArcOS-Frontend/assets/76709090/468b477e-94bb-41a1-86d5-69df71cda895)
The very component that renders the button is the same on both the vertical and horizontal taskbars

**Comment by ghost** [comment]
It happens even with the taskbar being docked.

**Comment by IzKuipers** [comment]
That's just a CSS class, has no way of changing the logo like that

Nothing can change it like this, not after the ~1s delay anyway

**Comment by ghost** [comment]
> That's just a CSS class, has no way of changing the logo like that
> 
> Nothing can change it like this, not after the ~1s delay anyway

huh, something is weird.

**Comment by ghost** [comment]
@IzKuipers If u have accented start button turned on before changing the position it works fine!!!

**Comment by ghost** [comment]
> @IzKuipers If u have accented start button turned on before changing the position it works fine!!!

For a split second

**Comment by IzKuipers** [comment]
I have already established that vertical taskbars have the issue and horizontal taskbars do not

There's practically no difference between the two even though they are two different components

**Comment by IzKuipers** [comment]
Vertical taskbars show the accented start button for about a second before it disappears, it's still present in the DOM tree and there's no CSS property affecting it in any way

**Comment by logangamesdaily** [comment]
It happens when the UserData is finished committing, and the UserData icon goes back to dark.

**Comment by IzKuipers** [comment]
Closing this as ArcOS v5 production is stopping as of February 20th 2024.
