### ISSUE TITLE
[Bug]: Error when attempting to upload custom backgrounds

### ISSUE THREAD

**Issue by Blockyheadman** [IzK-ArcOS/ArcOS-Frontend#27]
### What happened?

When attempting to upload a custom background image, it seems to fail and give this response in the DevTools page:
> NOTE: removed due to exposure of development ArcAPI

### Edition

Website

### If you are using a browser, which browsers are you seeing the problem on?

Microsoft Edge

### Other Browser(s)

(Haven't tested all browsers)

**Comment by Blockyheadman** [comment]
URLs still fail to function. When using a URL that doesn't end in `picture.png` or similar, it throws this error:
![image](https://github.com/IzK-ArcOS/ArcOS-Frontend/assets/80011716/5f26ebf5-a3cf-477c-941e-0dc9775d1539)

But when using a URL that has it, no errors are shown, but it doesn't load the background, instead heading to the default background. Uploading a file now works perfectly though!

**Comment by Blockyheadman** [comment]
The BG URL's i used were these:
[Win11 Dark BG](https://th.bing.com/th/id/OIP.29a3PDi_BPo8koLT-YBx0wHaEo?pid=ImgDet&rs=1)
[243170897.jpg](https://thumbs.dreamstime.com/b/ink-blend-artistic-hobby-colorful-abstract-bakgrund-ink-blend-artistic-hobby-colorful-abstract-bakgrund-purple-blue-glitter-paints-243170897.jpg) (Some random photo tbh)

**Comment by IzKuipers** [comment]
Deleted comment due to exposure of development ArcAPI

**Comment by Blockyheadman** [comment]
Ah sorry. Didn't know

**Comment by IzKuipers** [comment]
This issue has been resolved in recent commits, closing
