### ISSUE TITLE
[Feature]: Add a password confirm field when creating a new user

### ISSUE THREAD

**Issue by nulqwy** [IzK-ArcOS/ArcOS-Frontend#28]
### Describe the new feature

second field for password entry for confimational reasons (i mean it alrady exists in user password change action)

### Describe why the feature is useful

cuz i dont wanna realise i made a typo in the password and now locked out of it

**Comment by IzKuipers** [comment]
Closing, implemented

**Comment by IzKuipers** [comment]
![Image](https://github.com/IzK-ArcOS/ArcOS-Frontend/assets/76709090/411b46e7-94bf-493c-ae84-e3e6efa488b0)
