### ISSUE TITLE
[Bug]: Messaging app does too excessive caching

### ISSUE THREAD

**Issue by nulqwy** [IzK-ArcOS/ArcOS-Frontend#29]
### What happened?

Caching is not bad, but it is bad when data changes but old data is still cached. If new messages in the thread appear (or disappear) thread's cache is still not invalidated, resulting when viewing the thread in viewing outdated state.

possible resolution: invalidate cache of all threads whenever list of messages changes (or go with more fancier approach - only invalidate cache of affected threads)

### Edition

Desktop (Specfiy version below)

### ArcOS Version

v5.0.7 (`8844748ff16fc0335e6439de75890cf5065e88c2`)

### If you are using a browser, which browsers are you seeing the problem on?

Chrome

### Contact Detail(s)

\<github profile>

**Comment by IzKuipers** [comment]
Temporarily closing issue because I don't have clear indication as to a solution for the demonstrated problem.
