### ISSUE TITLE
[Feature]: Optional additional security for accounts

### ISSUE THREAD

**Issue by eversiege** [IzK-ArcOS/ArcOS-Frontend#37]
### Describe the new feature

I know this seems unnecessary but I would like to have some different ways to log in to my account, since one of my friends logged into someone else's account by guessing their passwords

### Describe why the feature is useful

idk fucking privacy or some shit...

**Comment by IzKuipers** [comment]
The unwanted access of your account is purely dependent on the security of your password. Therefor I think our priority should be on other parts of the project, not so much implementing features that not a lot of users will be using.

I'm closing #37 until we have more need for such an implementation.
