### ISSUE TITLE
Mobile website footer extends in height.

### ISSUE THREAD

**Issue by Blockyheadman** [IzK-ArcOS/ArcOS-Frontend#38]
### What happened?

Viewing the mobile website's footer shows that the footer extends an ubreasonable amount and text overflows onto another section of the site.
![Screenshot_20230715_133206_Chrome](https://github.com/IzK-ArcOS/ArcOS-Frontend/assets/80011716/7a8335ae-5045-4bb3-a903-afabd955e5a2)

### Edition

Website

### ArcOS Version

Mobile Site

### Other Browser(s)

Any

**Comment by IzKuipers** [comment]
In the future please create the issue in the corresponding repository

**Comment by Blockyheadman** [comment]
Got it. Will do next time

**Comment by IzKuipers** [comment]
I'm removing myself from this issue and I'm assigning @eversiege to take care of this

**Comment by eversiege** [comment]
Assigned task completed: https://github.com/IzK-ArcOS/ArcOS-Landing-v1/pull/1
