### ISSUE TITLE
[Bug]: ArcFS returns folder hierarchy of file when it should only do file name

### ISSUE THREAD

**Issue by logangamesdaily** [IzK-ArcOS/ArcOS-Frontend#39]
### What happened?

Opening a folder in File Explorer
![image](https://github.com/IzK-ArcOS/ArcOS-Frontend/assets/66440439/9b179dcc-432c-4e6c-9022-d7b47a98f69f)
![image](https://github.com/IzK-ArcOS/ArcOS-Frontend/assets/66440439/1f6f09ee-d302-48e3-9072-ab0b0d317661)

### Edition

Desktop (Specfiy version below)

### ArcOS Version

Latest source code compiled

### If you are using a browser, which browsers are you seeing the problem on?

Chrome

### Contact Detail(s)

@logan.games on Discord

**Comment by IzKuipers** [comment]
What API is this? ArcDev or Community?

**Comment by logangamesdaily** [comment]
Community

**Comment by IzKuipers** [comment]
Then I can successfully conclude that this is a Windows incompatibility since the Community API is hosted on Windows Server. This is likely because of the usage of `/` in Linux and `\` on Windows. I'm assigning @Spaceginner to make the path separator dynamic between operating systems.

**Comment by logangamesdaily** [comment]
im pretty sure space fixed it a bit ago

**Comment by logangamesdaily** [comment]
which is why he pinged you

**Comment by IzKuipers** [comment]
That appears to be correct, closing as per commit [642aa56](https://github.com/IzK-ArcOS/ArcOS-API-Rewritten/commit/642aa56844dffcd8e70b80bad6d40ad7f4307982)
