### ISSUE TITLE
[Bug]: Incorrect interpretetion of relative paths in ArcTerm

### ISSUE THREAD

**Issue by nulqwy** [IzK-ArcOS/ArcOS-Frontend#42]
### What happened?

idrk how to describe, but:

![image](https://github.com/IzK-ArcOS/ArcOS-Frontend/assets/97038786/64302b6b-f4e8-44ed-ada5-e16fff3baa57)

### Edition

Website

### ArcOS Version

v5.0.7 (`arcos.twi***.nl`)

### If you are using a browser, which browsers are you seeing the problem on?

Chrome

### Contact Detail(s)

\<github profile>

**Comment by IzKuipers** [comment]
API v2 incompatibility

**Comment by IzKuipers** [comment]
As with API v1, the idea here is to error out on API v2 if any path in a FS call contain `..`.

**Comment by nulqwy** [comment]
Fault lies on API v2 - it doesn't normalise `scopedPath` in `/fs/dir/get` responses

**Comment by IzKuipers** [comment]
Closing issue due to rewrite of `cd` in ArcOS-Frontend and update of `/fs/dir/get` in ArcOS-API-Rewritten
