### ISSUE TITLE
[Bug]: Text selector mouse icon not using host mouse cursor style.

### ISSUE THREAD

**Issue by Blockyheadman** [IzK-ArcOS/ArcOS-Frontend#44]
### What happened?

When writing text, the mouse cursor uses the built-in ArcOS editing cursor instead of the host cursor.

### Edition

Website

### If you are using a browser, which browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge, Opera/(GX)

### Other Browser(s)

Any/All + Desktop

**Comment by IzKuipers** [comment]
This only applies to the ArcTerm window due to an incorrect CSS query
