### ISSUE TITLE
[Bug]: ArcTerm line prefix dissapears after running `read` alone.

### ISSUE THREAD

**Issue by Blockyheadman** [IzK-ArcOS/ArcOS-Frontend#45]
### What happened?

When running the read command with or without any arguments, causes the prefix to disappear indefinitely. This also stays after a reset of local storage.
![image](https://github.com/IzK-ArcOS/ArcOS-Frontend/assets/80011716/8216ef2b-0ce7-4cb9-b73b-25944df2cc78)

### Edition

Website

### Other Browser(s)

All Browsers and desktop

**Comment by IzKuipers** [comment]
Could be a placebo effect? I can't reproduce

**Comment by Blockyheadman** [comment]
Closing issue as complete. Seems to be I somehow modified the prefix. Thanks for the help!
