### ISSUE TITLE
[Bug]: Server select ui empty when server list empty

### ISSUE THREAD

**Issue by Blockyheadman** [IzK-ArcOS/ArcOS-Frontend#46]
### What happened?

When running ArcOS without any servers available and going to the server select screen leaves it entirely empty. I think it would be best to disable is if there are no servers attached so users see this after FTS.

![image](https://github.com/IzK-ArcOS/ArcOS-Frontend/assets/80011716/1152182b-15bb-43b5-b725-8fe921e309f1)

### Edition

Desktop (Specfiy version below)

### ArcOS Version

Any

### Other Browser(s)

Any

**Comment by IzKuipers** [comment]
Known bug: just hadn't created an issue for it

**Comment by IzKuipers** [comment]
This bug has been resolved with the release of 5.0.9
