### ISSUE TITLE
[Feature]: Force first-time users to enter `community.arcapi.nl` by default unless requested

### ISSUE THREAD

**Issue by eversiege** [IzK-ArcOS/ArcOS-Frontend#48]
### Describe the new feature

As per title, proposing the default server to push to correct destination by default so users don't feel left out without reading the website. 

### Describe why the feature is useful

Users nowadays have short attention span - if they have to go different route, let alone join a Discord server to use something for the first time - they will instantly click off. This is one way to promise user's attention span by allowing them to experience the system without clicking off the front-end.

**Comment by IzKuipers** [comment]
This issue has already been implemented starting with ArcOS 5.0.9. Your statement about attention-span is indeed correct and something we should definitely consider, though I already thought of this and set the default API value of the First Time Setup to `community.arcapi.nl`.

> Note to team: we should move `community.arcapi.nl` to our VPS and off of the Cortex.
