### ISSUE TITLE
Deploy auto-updating frontend `web.izk-arcos.nl`

### ISSUE THREAD

**Issue by IzKuipers** [IzK-ArcOS/ArcOS-Frontend#49]
ArcOS will in the future have an auto-updating frontend likely on `web.izk-arcos.nl`. This frontend will periodically update on a 24hour(every midnight) basis. This means that it will always be relatively well updated so that we don't have to worry about keeping it updated ourselves. 

> Let the computers do the work, not us.

Use the clone command to get the repository into the folder:
```bash
git clone https://IzK-ArcOS/ArcOS-Frontend <directory>
```
And then periodically run a script similar to this to update it:
```bash
git pull
yarn build
```
> Note: `yarn build` outputs to `./dist` so the nginx entry must be `/path/to/frontend/dist`.

**Comment by eversiege** [comment]
I am sorry for how unprofessional this might sound but…

_…how the f#@k did we not do that yet?_

**Comment by IzKuipers** [comment]
Done!
