### ISSUE TITLE
Add r/place analogue

### ISSUE THREAD

**Issue by sawrams** [IzK-ArcOS/ArcOS-Frontend#50]
### Describe the new feature

I have an idea of adding r/place like app where people can draw something that others on the same API can see

### Describe why the feature is useful

It may make some users unite more with others and also expand community of ArcOS

**Comment by IzKuipers** [comment]
I'm assigning the backend team fulltime once the shared folders have been implemented, I'm putting it on the project board on a then created long term queue

This will likely be added to ArcOS 5.0.10

**Comment by IzKuipers** [comment]
Closing due to upcoming ArcOS changes (team informed)
