### ISSUE TITLE
Bug:ArmTerm showing wrong ArcOS version number

### ISSUE THREAD

**Issue by sawrams** [IzK-ArcOS/ArcOS-Frontend#51]
How to reproduce
1:Open ArcTerm
2:look at build number showing at startup of ArcTerm
![image](https://github.com/IzK-ArcOS/ArcOS-API-v1/assets/66771772/06d936a8-5505-4ec6-8a36-0a9416a4d1f8)

**Comment by IzKuipers** [comment]
Note: this is purely frontend related

The version number in the default greeting is pulled from the ArcOS version when the config is first created. if you type `atconf` in the ArcTerm app you'll see that the version is hardcoded in the JSON. This is something I will have to change to `$version`

**Comment by IzKuipers** [comment]
Resolved per https://github.com/IzK-ArcOS/ArcOS-Frontend/commit/3ceef20fa52d5fd0a8d1ed016e14675b067d392e
