### ISSUE TITLE
ToDo App

### ISSUE THREAD

**Issue by IzKuipers** [IzK-ArcOS/ArcOS-Frontend#56]
Make a todo app in ArcOS so I don't have to keep writing it down in my notebook

> References br$231215-782520-618506-698699

**Comment by ghost** [comment]
LMAO

**Comment by NikNikovsky** [comment]
that is honestly a good idea

**Comment by ghost** [comment]
> YES.

I just realized how stupid I am, I thought it was implemented...

**Comment by IzKuipers** [comment]
Yes?
