### ISSUE TITLE
Detect if an API requires AuthCode

### ISSUE THREAD

**Issue by IzKuipers** [IzK-ArcOS/ArcOS-Frontend#57]

**Comment by Blockyheadman** [comment]
My idea is if there's anything to identify server info, you can add a tag and make it an extra input if it has that tag.

**Comment by IzKuipers** [comment]
@Spaceginner Is it possible to make an endpoint that tells if the server has an authcode (so is private)?

**Comment by IzKuipers** [comment]
Due to CORS checking for a 403 isn't possible because CORS intercepts it for some reason.

**Comment by nulqwy** [comment]
> @Spaceginner Is it possible to make an endpoint that tells if the server has an authcode (so is private)?

`yes.`

**Comment by IzKuipers** [comment]
> Is it possible to make an endpoint that tells if the server has an authcode (so is private)?

@Spaceginner Has this been implemented by any chance?

**Comment by nulqwy** [comment]
i forgor ._.

**Comment by nulqwy** [comment]
implementing per... some recent commit

**Comment by nulqwy** [comment]
this: https://github.com/IzK-ArcOS/ArcOS-Frontend/commit/c6602b98cd7ab8db4d5878fe88d1b16f0a776b61
