### ISSUE TITLE
ArcTerm Team: `rm` help invalid

### ISSUE THREAD

**Issue by IzKuipers** [IzK-ArcOS/ArcOS-Frontend#65]
The `rm` help function in `src/ts/terminal/commands/rm.ts: Rm.help` still resembles the original `soundbus` help and must be updated to `rm`.

**Comment by Blockyheadman** [comment]
pushed changes. with the latest commit [`9b486b8`](https://github.com/IzK-ArcOS/ArcOS-Frontend/commit/9b486b8ff43bfe6d08a55ea595ecfd284bc5c975)
