### ISSUE TITLE
Add SECURITY.md files

### ISSUE THREAD

**Issue by Blockyheadman** [IzK-ArcOS/ArcOS-Frontend#66]
### Describe the new feature

This would be a file for the github repo describing our secrity policy and how we would handle security issues and how users would handle security issues.

### Describe why the feature is useful

It's useful so we can get security issues dealt with the correct way.

**Comment by eversiege** [comment]
The file is created, but is empty. I can take this issue and write a security/privacy policy.

**Comment by Blockyheadman** [comment]
alright thanks

**Comment by IzKuipers** [comment]
> The file is created, but is empty. I can take this issue and write a security/privacy policy.

@eversiege Then I suppose I can assign you to this issue?

**Comment by sawrams** [comment]
> > The file is created, but is empty. I can take this issue and write a security/privacy policy.
> 
> 
> 
> @eversiege Then I suppose I can assign you to this issue?

Im taking this issue, already assigned myself
