### ISSUE TITLE
[Bug]: Create new account button unreachable with 4+ rows of user accounts

### ISSUE THREAD

**Issue by eversiege** [IzK-ArcOS/ArcOS-Frontend#71]
### What happened?

_Reported by Azor, thank you!_

![chrome_bRQTFJIwuL](https://github.com/IzK-ArcOS/ArcOS-Frontend/assets/69052669/dca15344-6271-438a-8194-4ae64a147df1)

### Edition

Website

### ArcOS Version

5.0.9 - GitHub release rolling

### If you are using a browser, which browsers are you seeing the problem on?

Firefox, Chrome

### Other Browser(s)

N/A

### Contact Detail(s)

eversiege, Azor

**Comment by IzKuipers** [comment]
I've temporarily resolved this issue by adding a maximum size and vertical scroll to the selector. I've also changed the login to prioritize the AuthForm over the Selector.

**Comment by IzKuipers** [comment]
Closing issue: Login redesigned to eliminate this problem.
