### ISSUE TITLE
[Bug]: Clicking "Delete" in messages does not delete the message

### ISSUE THREAD

**Issue by eversiege** [IzK-ArcOS/ArcOS-Frontend#73]
### What happened?

When trying to click Delete in Messages, the pop up appears, but does not remove the message upon confirming.

### Edition

Desktop (Specfiy version below)

### ArcOS Version

5.0.9

**Comment by IzKuipers** [comment]
There are specific conditions when deleting messages, who owns the message?

**Comment by eversiege** [comment]
I received the message. But can’t you just remove it for yourself?

**Comment by IzKuipers** [comment]
Closing issue, resolved per https://github.com/IzK-ArcOS/ArcOS-Frontend/commit/9e96d2b848a3c60d39fb788c67b43fb343b14558
