### ISSUE TITLE
[Bug]: Prefix not showing correctly.

### ISSUE THREAD

**Issue by Blockyheadman** [IzK-ArcOS/ArcOS-Frontend#74]
### What happened?

The prefix in ArcTerm isn't showing as it should. I can tell this is an issue on web releases as of now due to the desktop app not doing the same thing. It's displaying as so
![image](https://github.com/IzK-ArcOS/ArcOS-Frontend/assets/80011716/82804070-36ec-463b-aa1e-d337f249401c)

### Edition

Website

### If you are using a browser, which browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge, Opera/(GX)

### Other Browser(s)

All

**Comment by IzKuipers** [comment]
Recently I changed the Prompt to use ArcTerm variables instead of the hardcoded `&` variables. This change affects any config file created before https://github.com/IzK-ArcOS/ArcOS-Frontend/commit/3ceef20fa52d5fd0a8d1ed016e14675b067d392e

**Comment by Blockyheadman** [comment]
ah okay. what changes should files have made for this to work once again?

**Comment by Blockyheadman** [comment]
i think it would be best if it could detect the previously named variables using regex and apply changes the next time the user opens arcterm. the only reason this would be a bad idea is if we decided to re-introduce the `&` variables for some reason

**Comment by IzKuipers** [comment]
![image](https://github.com/IzK-ArcOS/ArcOS-Frontend/assets/76709090/9c95d30e-5f3a-4886-a30a-47b3f0a7c694)
@eversiege how come?

**Comment by eversiege** [comment]
Ignore, GitHub on VS Code self-assigned.

**Comment by IzKuipers** [comment]
I see

**Comment by IzKuipers** [comment]
Closing as this is related to the ArcTerm configuration file of the user, not so much the codebase. This also implies that not a lot of users of the ArcOS Project actually experience this issue.
