### ISSUE TITLE
[Feature]: Wrap help output

### ISSUE THREAD

**Issue by Blockyheadman** [IzK-ArcOS/ArcOS-Frontend#75]
### Describe the new feature

The `help` command is getting to the point where it needs to be wrapped whenever it lists all the objects. Same can be told for `dir` and `ls` due to there not being a visible limit yet.

### Describe why the feature is useful

This would be easier to read for end users and benefits every party when using it.

**Comment by IzKuipers** [comment]
Closing because of temporary resolution in https://github.com/IzK-ArcOS/ArcOS-Frontend/commit/eee5c7545f10ffe6a4bcd96fe67afc9d19c2a89d
