### ISSUE TITLE
[Feature]: Add messaging functions and commands to ArcTerm(Including Term mode)

### ISSUE THREAD

**Issue by sawrams** [IzK-ArcOS/ArcOS-Frontend#77]
### Describe the new feature

with adding messaging functions to ArcTerm it will be possible to talk to people from even old devices using ArcTerm Isolated

### Describe why the feature is useful

Expands the functionality of ArcTerm and makes ArcTerm Isolated more useful

**Comment by IzKuipers** [comment]
Moving to halted
