### ISSUE TITLE
[Bug]: App icons don't show at startup

### ISSUE THREAD

**Issue by Blockyheadman** [IzK-ArcOS/ArcOS-Frontend#88]
When I was messing with settings, i noticed that changing the theme caused some icons to appear on the desktop.

https://github.com/IzK-ArcOS/ArcOS-Frontend/assets/80011716/964fb81b-44c5-4b02-8283-07d750f29ad4

**Comment by IzKuipers** [comment]
yeah already ran into that and I've implemented a fix for it, closing issue.
