### ISSUE TITLE
[Bug]: ArcOS setup does not start up

### ISSUE THREAD

**Issue by NikNikovsky** [IzK-ArcOS/ArcOS-Frontend#89]
### What happened?

The ArcOS setup does not want to start up, even with administrator perms.

Doing this on Windows

### Edition

Desktop (Specfiy version below)

### ArcOS Version

5.0.10

### Contact Detail(s)

@niknikovsky

**Comment by IzKuipers** [comment]
Windows 10 or 11?

**Comment by NikNikovsky** [comment]
11

**Comment by IzKuipers** [comment]
Is this issue still relevant?

**Comment by NikNikovsky** [comment]
I had to manually run it as admin.

**Comment by NikNikovsky** [comment]
Shouldn't it ask for that automatically?

**Comment by IzKuipers** [comment]
yes it should, unfortunately this issue is not related to ArcOS but sooner Electron-Builder which we use.
