### ISSUE TITLE
[Feature]: Make the Notes app

### ISSUE THREAD

**Issue by NikNikovsky** [IzK-ArcOS/ArcOS-Frontend#91]
### Describe the new feature

It basically allows you to take quick notes, could be a desktop widget (and should probably have [this](https://github.com/IzK-ArcOS/ArcOS-Frontend/issues/56) built into it)

### Describe why the feature is useful

I personally think that it could make it more like a real OS

**Comment by eversiege** [comment]
Duplicate of #68; not confirmed if the feature will be added or not. Mentioning @IzKuipers

**Comment by NikNikovsky** [comment]
not expecting it to be done

**Comment by IzKuipers** [comment]
Unfortunately no, this is because of an increased amount of stuff that has to be done, I'm simply too busy to finish it

(To DT: It is already in ArcOS Conceptual)
