### ISSUE TITLE
Changing your profile picture breaks the settings app

### ISSUE THREAD

**Issue by ArcBugRep** [IzK-ArcOS/ArcOS-Frontend#97]
I've tried to change my profile picture and the settings app broke...?

Screenshot: ![1aO2l3h](https://i.imgur.com/1aO2l3h.png)

> References br$574737-452877-767023-658997

**Comment by IzKuipers** [comment]
@andriemc

**Comment by ghost** [comment]
hi!

**Comment by IzKuipers** [comment]
just letting you know that I've converted [your report](https://bugrep.arcapi.nl/?rid=h666ouwwrugq2j9) to an issue

**Comment by ghost** [comment]
mhm i see
