### ISSUE TITLE
[Bug]: Flashing Lights

### ISSUE THREAD

**Issue by NikNikovsky** [IzK-ArcOS/ArcOS-Frontend#98]
### What happened?

You can see everything [here](https://youtu.be/ooBP_6gXsrE)

### Edition

Desktop (Specfiy version below)

### ArcOS Version

5.0.11

### Contact Detail(s)

NikNikovsky

**Comment by IzKuipers** [comment]
I'm sorry what exactly is happening here? It doesn't help that the recording is 360p

**Comment by NikNikovsky** [comment]
that's probably because I just uploaded it

**Comment by NikNikovsky** [comment]
anyways, I am basically going into the settings app and switching between themes, wallpapers, and visuals. That causes the screen to flicker

**Comment by IzKuipers** [comment]
there is no flickering anywhere in the recording

**Comment by NikNikovsky** [comment]
now that is odd.

**Comment by IzKuipers** [comment]
could it be a hardware issue?

**Comment by NikNikovsky** [comment]
it only ever happened in ArcOS and in PCBS 2, even after a driver update

**Comment by IzKuipers** [comment]
maybe try recording it using a camera

**Comment by NikNikovsky** [comment]
alright

**Comment by IzKuipers** [comment]
> it only ever happened in ArcOS and in PCBS 2, even after a driver update

odd

**Comment by IzKuipers** [comment]
does it not happen on any other Electron based applications (VSCode, Discord)?

**Comment by NikNikovsky** [comment]
nope

**Comment by IzKuipers** [comment]
I've been doing this for years and I've never seen anything like this, damn

Could you send me a summary of your system? CPU, GPU, the works?

**Comment by NikNikovsky** [comment]
Processor: 11th Gen Intel(R) Core(TM) i5-11400 @ 2.60GHz, 2592 Mhz, 6 Core(s), 12 Logical Processor(s)
![obraz](https://github.com/IzK-ArcOS/ArcOS-Frontend/assets/75254052/049d337e-e1a0-4038-adc9-4bb9d4ad73ed)

**Comment by NikNikovsky** [comment]
you know what's even weirder?
The flickering is gone?

**Comment by IzKuipers** [comment]
> you know what's even weirder?
> 
> The flickering is gone?

Has this flickering occurred before today? Did you restart before the flickering went away?

**Comment by NikNikovsky** [comment]
> > you know what's even weirder?
> > The flickering is gone?
> 
> Has this flickering occurred before today? Did you restart before the flickering went away?

Yes, the flickering has been going on for a few days and, no there was no restart

**Comment by IzKuipers** [comment]
https://www.nvidia.com/en-us/geforce/forums/game-ready-drivers/13/305278/gtx-1070-black-screen-flickering/ may be applicable, not sure. In either way not a problem on ArcOS' end.

**Comment by NikNikovsky** [comment]
I updated the driver, will check later.
Closing this for now

**Comment by IzKuipers** [comment]
Alright
